### ISSUE TITLE
Update JETGPIO to latest version?

### ISSUE THREAD

**Issue by democat3457** [raoz/jetgpio-sys#1]
JETGPIO seems to support the Orin fully now, is it possible that this crate could be updated to include that compatibility? Would love to be able to use this with the Orin.

**Comment by raoz** [comment]
I noticed that there's a script upstream for enabling the PWM clocks, would it be helpful if I also implemented a small function to do this in this crate? ( https://github.com/Rubberazer/JETGPIO/blob/main/scripts/pwm_enabler.sh )

**Comment by democat3457** [comment]
Maybe, but it seems like that script is automatically ran by a service when the makefile runs?

**Comment by raoz** [comment]
Yes, but this crate does not use the upstream Makefile, so if you never install upstream directly, then it's never run.

**Comment by democat3457** [comment]
Ah yea, then that would be nice- maybe if there's some way to hook it into gpioInitialise?
