### ISSUE TITLE
Any example how to use this crate

### ISSUE THREAD

**Issue by maniema4real** [raoz/jetgpio-sys#13]
I am looking for something like this as I believe, I can control my servo motor connected to my PCA9685 board on my Jetson nano, but I don't manage to understand how to use this crate. An example would be very much welcomed.

**Comment by raoz** [comment]
Heya!

I added an [example](../../examples/blink.rs) of a simple led blinker. This library is quite low-level and maps directly to [JETGPIO](https://github.com/Rubberazer/JETGPIO/) C functions, so their [I²C example](https://github.com/Rubberazer/JETGPIO/blob/main/EXAMPLES_C/jetgpio_i2c_example.c) is probably the most relevant for you.

Additionally, you can consider using [the `i2cdev` crate](https://docs.rs/i2cdev/latest/i2cdev/) instead for a high-level I²C interface using the Linux kernel. I have not tried either approach myself, so I don't know which approach would be better.

All the best
Rao Zvorovski
